In [34]:
import pandas as pd

In [39]:
df = pd.read_excel("Superstore_ex.xlsx")

In [40]:
df.head()

,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country_Region,City,State,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit
0,CA-2016-156587,2016-03-07,2016-03-08,First Class,AB-10015,Aaron Bergman,Consumer,United States,Seattle,Washington,98103,West,FUR-CH-10004477,Furniture,Chairs,"Global Push Button Manager's Chair, Indigo",48.712,1,0.2,5.4801
1,CA-2016-156587,2016-03-07,2016-03-08,First Class,AB-10015,Aaron Bergman,Consumer,United States,Seattle,Washington,98103,West,OFF-AR-10001427,Office Supplies,Art,Newell 330,17.940,3,0.0,4.6644
2,CA-2016-156587,2016-03-07,2016-03-08,First Class,AB-10015,Aaron Bergman,Consumer,United States,Seattle,Washington,98103,West,OFF-ST-10002344,Office Supplies,Storage,"Carina 42""Hx23 3/4""W Media Storage Unit",242.940,3,0.0,4.8588
3,CA-2016-152905,2016-02-18,2016-02-24,Standard Class,AB-10015,Aaron Bergman,Consumer,United States,Arlington,Texas,76017,Central,OFF-ST-10000321,Office Supplies,Storage,Akro Stacking Bins,12.624,2,0.2,-2.5248
4,CA-2018-140935,2018-11-10,2018-11-12,First Class,AB-10015,Aaron Bergman,Consumer,United States,Oklahoma City,Oklahoma,73120,Central,TEC-PH-10000562,Technology,Phones,Samsung Convoy 3,221.980,2,0.0,62.1544

In [41]:
df.isnull().sum()

Order_ID          0
Order_Date        0
Ship_Date         0
Ship_Mode         0
Customer_ID       0
Customer_Name     0
Segment           0
Country_Region    0
City              0
State             0
Postal_Code       0
Region            0
Product_ID        0
Category          0
Sub_Category      0
Product_Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
dtype: int64

In [43]:
df.to_csv("superstore_cl.csv", index=False)

In [45]:
pd.read_csv("superstore_cl.csv")

,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country_Region,City,State,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit
0,CA-2016-156587,2016-03-07,2016-03-08,First Class,AB-10015,Aaron Bergman,Consumer,United States,Seattle,Washington,98103,West,FUR-CH-10004477,Furniture,Chairs,"Global Push Button Manager's Chair, Indigo",48.712,1,0.2,5.4801
1,CA-2016-156587,2016-03-07,2016-03-08,First Class,AB-10015,Aaron Bergman,Consumer,United States,Seattle,Washington,98103,West,OFF-AR-10001427,Office Supplies,Art,Newell 330,17.940,3,0.0,4.6644
2,CA-2016-156587,2016-03-07,2016-03-08,First Class,AB-10015,Aaron Bergman,Consumer,United States,Seattle,Washington,98103,West,OFF-ST-10002344,Office Supplies,Storage,"Carina 42""Hx23 3/4""W Media Storage Unit",242.940,3,0.0,4.8588
3,CA-2016-152905,2016-02-18,2016-02-24,Standard Class,AB-10015,Aaron Bergman,Consumer,United States,Arlington,Texas,76017,Central,OFF-ST-10000321,Office Supplies,Storage,Akro Stacking Bins,12.624,2,0.2,-2.5248
4,CA-2018-140935,2018-11-10,2018-11-12,First Class,AB-10015,Aaron Bergman,Consumer,United States,Oklahoma City,Oklahoma,73120,Central,TEC-PH-10000562,Technology,Phones,Samsung Convoy 3,221.980,2,0.0,62.1544
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,CA-2018-152471,2018-07-08,2018-07-08,Same Day,ZD-21925,Zuschuss Donatelli,Consumer,United States,Jacksonville,Florida,32216,South,TEC-PH-10002824,Technology,Phones,Jabra SPEAK 410 Multidevice Speakerphone,823.960,5,0.2,51.4975
9990,CA-2018-152471,2018-07-08,2018-07-08,Same Day,ZD-21925,Zuschuss Donatelli,Consumer,United States,Jacksonville,Florida,32216,South,OFF-PA-10004965,Office Supplies,Paper,Xerox 1921,15.984,2,0.2,4.9950
9991,CA-2018-167682,2018-04-03,2018-04-09,Standard Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,Richmond,Indiana,47374,Central,FUR-FU-10003799,Furniture,Furnishings,"Seth Thomas 13 1/2"" Wall Clock",71.120,4,0.0,22.0472
9992,CA-2018-167682,2018-04-03,2018-04-09,Standard Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,Richmond,Indiana,47374,Central,TEC-PH-10000673,Technology,Phones,Plantronics Voyager Pro HD - Bluetooth Headset,259.960,4,0.0,124.7808
9993,CA-2019-141481,2019-06-11,2019-06-14,First Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,Los Angeles,California,90036,West,OFF-AP-10004532,Office Supplies,Appliances,Kensington 6 Outlet Guardian Standard Surge Pr...,61.440,3,0.0,16.5888

In [12]:
pip install pandas sqlalchemy pymysql

Requirement already satisfied: pandas in C:\Users\ThinkPad-T570Worksta\anaconda3\anaconda3_2025\Lib\site-packages (2.2.3)
Requirement already satisfied: sqlalchemy in C:\Users\ThinkPad-T570Worksta\anaconda3\anaconda3_2025\Lib\site-packages (2.0.39)
Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\ThinkPad-T570Worksta\anaconda3\anaconda3_2025\Lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ThinkPad-T570Worksta\anaconda3\anaconda3_2025\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\ThinkPad-T570Worksta\anaconda3\anaconda3_2025\Lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\ThinkPad-T570Worksta\anaconda3\anaconda3_2025\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: greenlet!=0.4.17 in C:\Users\ThinkPad-T570Worksta\anaconda3\anaconda3_2025\Lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\ThinkPad-T570Worksta\anaconda3\anaconda3_2025\Lib\site-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: six>=1.5 in C:\Users\ThinkPad-T570Worksta\anaconda3\anaconda3_2025\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [46]:
from sqlalchemy import create_engine

In [48]:
# MySQL connection 
engine = create_engine("mysql+pymysql://root:root@localhost/superstore_db")

In [52]:
df.

(9994, 20)

In [53]:
# Upload to MySQL
df.to_sql("superstore", con=engine, if_exists="replace", index=False)
print("Data uploaded successfully!")

Data uploaded successfully!

In [54]:
df.count()

Order_ID          9994
Order_Date        9994
Ship_Date         9994
Ship_Mode         9994
Customer_ID       9994
Customer_Name     9994
Segment           9994
Country_Region    9994
City              9994
State             9994
Postal_Code       9994
Region            9994
Product_ID        9994
Category          9994
Sub_Category      9994
Product_Name      9994
Sales             9994
Quantity          9994
Discount          9994
Profit            9994
dtype: int64